//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvictaAPI
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/InvictaAPI", ConfigurationName="InvictaAPI.InvictaAPI_Port")]
    public interface InvictaAPI_Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/InvictaAPI:GetJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<InvictaAPI.GetJSON_Result> GetJSONAsync(InvictaAPI.GetJSON request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetJSON", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/InvictaAPI", IsWrapped=true)]
    public partial class GetJSON
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/InvictaAPI", Order=0)]
        public string requestName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/InvictaAPI", Order=1)]
        public string requestParams;
        
        public GetJSON()
        {
        }
        
        public GetJSON(string requestName, string requestParams)
        {
            this.requestName = requestName;
            this.requestParams = requestParams;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetJSON_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/InvictaAPI", IsWrapped=true)]
    public partial class GetJSON_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/InvictaAPI", Order=0)]
        public string return_value;
        
        public GetJSON_Result()
        {
        }
        
        public GetJSON_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface InvictaAPI_PortChannel : InvictaAPI.InvictaAPI_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class InvictaAPI_PortClient : System.ServiceModel.ClientBase<InvictaAPI.InvictaAPI_Port>, InvictaAPI.InvictaAPI_Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public InvictaAPI_PortClient() : 
                base(InvictaAPI_PortClient.GetDefaultBinding(), InvictaAPI_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.InvictaAPI_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InvictaAPI_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(InvictaAPI_PortClient.GetBindingForEndpoint(endpointConfiguration), InvictaAPI_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InvictaAPI_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(InvictaAPI_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InvictaAPI_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(InvictaAPI_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InvictaAPI_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InvictaAPI.GetJSON_Result> InvictaAPI.InvictaAPI_Port.GetJSONAsync(InvictaAPI.GetJSON request)
        {
            return base.Channel.GetJSONAsync(request);
        }
        
        public System.Threading.Tasks.Task<InvictaAPI.GetJSON_Result> GetJSONAsync(string requestName, string requestParams)
        {
            InvictaAPI.GetJSON inValue = new InvictaAPI.GetJSON();
            inValue.requestName = requestName;
            inValue.requestParams = requestParams;
            return ((InvictaAPI.InvictaAPI_Port)(this)).GetJSONAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.InvictaAPI_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.InvictaAPI_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://127.0.0.1:9602/InvictaWebClient/WS/Retailing Enterprises%252C LLC/Codeunit" +
                        "/InvictaAPI");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return InvictaAPI_PortClient.GetBindingForEndpoint(EndpointConfiguration.InvictaAPI_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return InvictaAPI_PortClient.GetEndpointAddress(EndpointConfiguration.InvictaAPI_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            InvictaAPI_Port,
        }
    }
}
